#:schema https://dystroy.org/bacon/.bacon.schema.json

[jobs.check]
command = ["cargo", "check"]
need_stdout = false
scroll_anchor = "auto"

[jobs.check-all]
command = ["cargo", "check", "--all-targets"]
need_stdout = false
scroll_anchor = "auto"

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false
scroll_anchor = "auto"

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false
scroll_anchor = "auto"

[jobs.test]
command = ["cargo", "test"]
need_stdout = true
scroll_anchor = "auto"

[jobs.nextest]
command = [
    "cargo", "nextest", "run",
    "--hide-progress-bar", "--failure-output", "final"
]
need_stdout = true
analyzer = "nextest"
scroll_anchor = "auto"
