//! Generates one `#[test]` per file in `examples/`, asserting each
//! parses with no error. Regenerated from whatever `examples/` currently
//! contains, so the test suite can never silently drift out of sync with
//! it — mirrors `crates/lexer/build.rs`'s approach, one layer up the
//! pipeline.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/parser should be two directories below the repo root")
        .to_path_buf();
    let examples_dir = repo_root.join("examples");

    println!("cargo:rerun-if-changed={}", examples_dir.display());

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit by hand.\n\n");

    generate_example_file_tests(&examples_dir, &mut out);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("example_tests.rs"), out).expect("failed to write generated tests");
}

/// Emits one test per `.fig` file directly under `examples_dir`.
fn generate_example_file_tests(examples_dir: &Path, out: &mut String) {
    let mut fig_files = Vec::new();
    collect_files_with_extension(examples_dir, "fig", &mut fig_files);
    fig_files.sort();

    for path in fig_files {
        let content = fs::read_to_string(&path).expect("failed to read example .fig file");
        let stem = path
            .file_stem()
            .expect("example file should have a name")
            .to_string_lossy();
        let test_name = format!("example_{}", sanitize_ident(&stem));
        let display_path = path
            .file_name()
            .expect("example file should have a name")
            .to_string_lossy()
            .into_owned();
        write_parse_ok_test(out, &test_name, &display_path, &content);
    }
}

fn write_parse_ok_test(out: &mut String, test_name: &str, display_path: &str, source: &str) {
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {test_name}() {{").unwrap();
    writeln!(out, "    let source = {source:?};").unwrap();
    writeln!(
        out,
        "    let tokens = lexer::tokenize_all(source).expect(\"{display_path} should lex cleanly\");"
    )
    .unwrap();
    writeln!(
        out,
        "    if let Err(errs) = parser::module().parse(parser::input(tokens)).into_result() {{"
    )
    .unwrap();
    writeln!(
        out,
        "        panic!(\"failed to parse {display_path}: {{errs:?}}\\n---\\n{{source}}\\n---\");",
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out.push('\n');
}

fn collect_files_with_extension(dir: &Path, extension: &str, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files_with_extension(&path, extension, out);
        } else if path.extension().is_some_and(|ext| ext == extension) {
            out.push(path);
        }
    }
}

/// Turns an arbitrary file stem into a valid Rust identifier fragment:
/// `player-controller` -> `player_controller`.
fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
