[package]
name = "parser"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Parses roo-lang tokens into an AST"
readme = "../../README.md"
license.workspace = true
keywords = ["parser", "ast", "compiler"]
categories = ["compilers", "parser-implementations"]
# repository.workspace = true

[dependencies]
chumsky = { version = "0.13.0", features = ["pratt"] }
lexer = { version = "0.1.0", path = "../lexer" }
ast = { version = "0.1.0", path = "../ast" }
intern = { version = "0.1.0", path = "../intern" }

[lints]
workspace = true
