[package]
name = "typecheck"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "roo-lang's type checker -- lowers ast::Ty into TyKind terms and solves the resulting constraints"
readme = "../../README.md"
license.workspace = true
keywords = ["typecheck", "types", "inference"]
categories = ["compilers"]
# repository.workspace = true

[dependencies]
ast = { version = "0.1.0", path = "../ast" }
intern = { version = "0.1.0", path = "../intern" }
slotmap = "1.1.1"
indexmap = "2"
thiserror = "2.0.20"
union-find = "0.4.3"
diagnostics = { version = "0.1.0", path = "../diagnostics" }
diagnostics-derive = { version = "0.1.0", path = "../diagnostics-derive" }

[dev-dependencies]
lexer = { version = "0.1.0", path = "../lexer" }
parser = { version = "0.1.0", path = "../parser" }
chumsky = { version = "0.13.0", features = ["pratt"] }
indoc = "2.0.7"

[lints]
workspace = true
