use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crates/lexer should be two directories below the repo root")
        .to_path_buf();
    let book_src = repo_root.join("book").join("src");
    let examples_dir = repo_root.join("examples");

    println!("cargo:rerun-if-changed={}", book_src.display());
    println!("cargo:rerun-if-changed={}", examples_dir.display());

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit by hand.\n\n");

    generate_book_snippet_tests(&book_src, &mut out);
    generate_example_file_tests(&examples_dir, &mut out);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("book_snippets_tests.rs"), out)
        .expect("failed to write generated tests");
}

fn generate_book_snippet_tests(book_src: &Path, out: &mut String) {
    let mut md_files = Vec::new();
    collect_files_with_extension(book_src, "md", &mut md_files);
    md_files.sort();

    for path in md_files {
        let content = fs::read_to_string(&path).expect("failed to read book markdown file");
        let relative = path.strip_prefix(book_src).unwrap_or(&path);
        let test_stem = sanitize_ident(&relative.with_extension("").to_string_lossy());

        for (i, block) in extract_roo_blocks(&content).into_iter().enumerate() {
            let test_name = format!("book_{test_stem}_block_{i}");
            let display_path = relative.display().to_string();
            write_lex_ok_test(out, &test_name, &display_path, i, &block);
        }
    }
}

fn generate_example_file_tests(examples_dir: &Path, out: &mut String) {
    let mut roo_files = Vec::new();
    collect_files_with_extension(examples_dir, "roo", &mut roo_files);
    roo_files.sort();

    for path in roo_files {
        let content = fs::read_to_string(&path).expect("failed to read example .roo file");
        let stem = path
            .file_stem()
            .expect("example file should have a name")
            .to_string_lossy();
        let test_name = format!("example_{}", sanitize_ident(&stem));
        let display_path = path
            .file_name()
            .expect("example file should have a name")
            .to_string_lossy()
            .into_owned();
        write_lex_ok_test(out, &test_name, &display_path, 0, &content);
    }
}

fn write_lex_ok_test(
    out: &mut String,
    test_name: &str,
    display_path: &str,
    block_index: usize,
    source: &str,
) {
    writeln!(out, "#[test]").unwrap();
    writeln!(out, "fn {test_name}() {{").unwrap();
    writeln!(out, "    let source = {source:?};").unwrap();
    writeln!(out, "    if let Err(err) = lexer::tokenize_all(source) {{").unwrap();
    writeln!(
        out,
        "        panic!(\"failed to lex {display_path} block {block_index}: {{err:?}}\\n---\\n{{source}}\\n---\");",
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    out.push('\n');
}

fn extract_roo_blocks(markdown: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut lines = markdown.lines();

    while let Some(line) = lines.by_ref().next() {
        if line.trim() != "```roo" {
            continue;
        }
        let mut block = String::new();
        for inner in lines.by_ref() {
            if inner.trim() == "```" {
                break;
            }
            block.push_str(inner);
            block.push('\n');
        }
        blocks.push(block);
    }

    blocks
}

fn collect_files_with_extension(dir: &Path, extension: &str, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files_with_extension(&path, extension, out);
        } else if path.extension().is_some_and(|ext| ext == extension) {
            out.push(path);
        }
    }
}

fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
